services:
  - type: web
    name: real-estate-genie
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); user, created = User.objects.get_or_create(username='admin', defaults={'is_staff': True, 'is_superuser': True}); user.set_password('Sales@2025'); user.is_staff = True; user.is_superuser = True; user.save(); print('Admin password updated to Sales@2025')"
      python manage.py collectstatic --noinput
    startCommand: gunicorn RealEstateGenie.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: RealEstateGenie.settings
