# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('studio', 'Studio'), ('loft', 'Loft')], max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('square_feet', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='rent_properties/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_rental_yield', models.DecimalField(decimal_places=2, help_text='Annual rental yield percentage', max_digits=5)),
                ('cap_rate', models.DecimalField(decimal_places=2, help_text='Capitalization rate percentage', max_digits=5)),
                ('cash_flow', models.DecimalField(decimal_places=2, help_text='Monthly cash flow', max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, help_text='Return on investment percentage', max_digits=5)),
            ],
            options={
                'verbose_name': 'Rent Property',
                'verbose_name_plural': 'Rent Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rent_properties/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.rentproperty')),
            ],
        ),
    ]