# Generated by Django 4.2.7 on 2025-09-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title/name', max_length=200)),
                ('url', models.URLField(help_text='The URL to link to')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('rent', 'Rent Properties'), ('sale', 'Sale Properties'), ('events', 'Events')], help_text='Which page this link appears on', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the link')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Link',
                'verbose_name_plural': 'Page Links',
                'ordering': ['page', 'order', 'title'],
            },
        ),
    ]
