# Generated by Django 4.2.7 on 2025-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Widget name/identifier', max_length=200)),
                ('script_content', models.TextField(help_text='The script tag content to append to the page')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('rent', 'Rent Properties'), ('sale', 'Sale Properties'), ('events', 'Events')], help_text='Which page this widget appears on', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this widget is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Widget',
                'verbose_name_plural': 'Page Widgets',
                'ordering': ['page', 'order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='PageLink',
        ),
    ]
