# Generated by Django 4.2.7 on 2025-09-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_links', '0002_pagewidget_delete_pagelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['page', 'order'], 'verbose_name': 'Page Widget', 'verbose_name_plural': 'Page Widgets'},
        ),
        migrations.RemoveField(
            model_name='pagewidget',
            name='name',
        ),
    ]
