# Generated by Django 4.2.7 on 2025-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_links', '0003_alter_pagewidget_options_remove_pagewidget_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['page'], 'verbose_name': 'Page Widget', 'verbose_name_plural': 'Page Widgets'},
        ),
        migrations.RemoveField(
            model_name='pagewidget',
            name='order',
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='script_content',
            field=models.TextField(help_text='The script tag content to append to the page', verbose_name='Script'),
        ),
    ]
