# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('commercial', 'Commercial')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('square_feet', models.PositiveIntegerField()),
                ('lot_size', models.DecimalField(decimal_places=2, help_text='Lot size in square feet', max_digits=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='sale_properties/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, help_text='Price per square foot', max_digits=10)),
                ('appreciation_rate', models.DecimalField(decimal_places=2, help_text='Annual appreciation rate percentage', max_digits=5)),
                ('market_value', models.DecimalField(decimal_places=2, help_text='Current market value', max_digits=12)),
                ('investment_potential', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
            ],
            options={
                'verbose_name': 'Sale Property',
                'verbose_name_plural': 'Sale Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sale_properties/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sale.saleproperty')),
            ],
        ),
    ]