# Generated by Django 4.2.7 on 2025-09-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalePropertyImage',
        ),
    ]
